## functions for circularity detection (partially generated by AI, to be optimized)
from .imports import *
from .functions import *

COMPLEMENT = str.maketrans("ACGTUNacgtun", "TGCANtgcanN".ljust(12, "N")[:12])
_COMPLEMENT_MAP = {
    "A": "T", "T": "A", "C": "G", "G": "C", "U": "A",
    "a": "t", "t": "a", "c": "g", "g": "c", "u": "a",
    "N": "N", "n": "n",
}
_WORKER_STATE = {}
PARALLEL_THRESHOLD = 32

def kmers_in(seq: str, k: int):
    """Returns the kmers in the sequences seq."""
    n = len(seq)
    if n < k:
        return set()
    seq = seq.upper()
    return {seq[i:i + k] for i in range(n - k + 1)}

def reverse_complement(seq: str) -> str:
    return "".join(_COMPLEMENT_MAP.get(b, "N") for b in reversed(seq))

def hamming_mismatches(a: str, b: str) -> int:
    return sum(1 for x, y in zip(a, b) if x.upper() != y.upper())

def best_overlap(suffix_source: str, prefix_target: str, min_len: int,
                  max_len: int, max_mismatch_rate: float):
    """
    Looks for the longest overlap where `suffix_source` is the beginning of `prefix_target`, tolerating a given mismatch rate. 
    Returns (length, mismatch_rate) or None.
    """
    max_possible = min(len(suffix_source), len(prefix_target), max_len)
    best = None
    for length in range(max_possible, min_len - 1, -1):
        a = suffix_source[-length:]
        b = prefix_target[:length]
        mism = hamming_mismatches(a, b)
        rate = mism / length
        if rate <= max_mismatch_rate:
            best = (length, rate)
            break
    return best

def build_head_index(variants, seed_len, max_overlap):
    """
    variants : dict {(id, orientation): sequence}
    Indexes all the kmers present in the START region (max_overlap first characters).
    Returns dict {kmer: set((id, orientation), ...)}
    """
    index = defaultdict(set)
    for key, seq in variants.items():
        head = seq[:max_overlap]
        for kmer in kmers_in(head, seed_len):
            index[kmer].add(key)
    return index

def _init_worker(sequences, variants, head_index, seed_len, min_overlap,
                  max_overlap, max_mismatch_rate):
    """Initialisation of worker."""
    global _WORKER_STATE
    _WORKER_STATE = {
        "sequences": sequences,
        "variants": variants,
        "head_index": head_index,
        "seed_len": seed_len,
        "min_overlap": min_overlap,
        "max_overlap": max_overlap,
        "max_mismatch_rate": max_mismatch_rate,
    }

def _self_task(seq_id):
    st = _WORKER_STATE
    seq = st["sequences"][seq_id]
    safe_max = min(st["max_overlap"], len(seq) // 2)  # jamais la séquence entière
    if safe_max < st["min_overlap"]:
        return None
    tail_kmers = kmers_in(seq[-safe_max:], st["seed_len"])
    head_kmers = kmers_in(seq[:safe_max], st["seed_len"])
    if not (tail_kmers & head_kmers):
        return None
    overlap = best_overlap(seq, seq, st["min_overlap"], safe_max, st["max_mismatch_rate"])
    if overlap:
        length, rate = overlap
        return {"sequences": (seq_id,), "overlap_len": length, "mismatch_rate": rate}
    return None

def _cross_task(source_key):
    """source_key = (id_a, orientation_a). Returns hits between the source sequence and all the available candidates  """
    st = _WORKER_STATE
    id_a, orient_a = source_key
    seq_a = st["variants"][source_key]
    tail = seq_a[-st["max_overlap"]:]
    tail_kmers = kmers_in(tail, st["seed_len"])
 
    candidates = set()
    for kmer in tail_kmers:
        candidates |= st["head_index"].get(kmer, set())
    candidates = {c for c in candidates if c[0] != id_a}
 
    hits = []
    for id_b, orient_b in candidates:
        seq_b = st["variants"][(id_b, orient_b)]
        overlap = best_overlap(seq_a, seq_b, st["min_overlap"], st["max_overlap"], st["max_mismatch_rate"])
        if overlap:
            length, rate = overlap
            hits.append({
                "from": source_key,
                "to": (id_b, orient_b),
                "overlap_len": length,
                "mismatch_rate": rate,
            })
    return hits

def check_self_circularity(sequences, seed_len, min_overlap, max_overlap, max_mismatch_rate, processes=1):
    """Screens a sequence for an overlap with itself."""
    ids = list(sequences.keys())
 
    if processes <= 1 or len(ids) < PARALLEL_THRESHOLD:
        _init_worker({}, {}, {}, seed_len, min_overlap, max_overlap, max_mismatch_rate)
        _WORKER_STATE["sequences"] = sequences
        return [r for r in (_self_task(seq_id) for seq_id in ids) if r]
 
    with ProcessPoolExecutor(
        max_workers=processes,
        initializer=_init_worker,
        initargs=(sequences, {}, {}, seed_len, min_overlap, max_overlap, max_mismatch_rate),
    ) as executor:
        results = list(executor.map(_self_task, ids, chunksize=max(1, len(ids) // (processes * 4) or 1)))
    return [r for r in results if r]

def check_cross_circularity(sequences, seed_len, min_overlap, max_overlap, max_mismatch_rate, processes=1):
    """
    Constructs the complete graph of overlaps between distincts sequences.
    Return a list of edges defined as {"from", "to", "overlap_len", "mismatch_rate"}.
    """
    # Variants: forward (+), reverse (-)
    variants = {}
    for seq_id, seq in sequences.items():
        variants[(seq_id, "+")] = seq
        variants[(seq_id, "-")] = reverse_complement(seq)
 
    head_index = build_head_index(variants, seed_len, max_overlap)
    source_keys = list(variants.keys())  # 2 x N sources (+ et - de chaque séquence)
 
    if processes <= 1 or len(sequences) < PARALLEL_THRESHOLD:
        _init_worker(sequences, variants, head_index, seed_len, min_overlap, max_overlap, max_mismatch_rate)
        all_hits = [_cross_task(key) for key in source_keys]
    else:
        with ProcessPoolExecutor(
            max_workers=processes,
            initializer=_init_worker,
            initargs=(sequences, variants, head_index, seed_len, min_overlap, max_overlap, max_mismatch_rate),
        ) as executor:
            all_hits = list(executor.map(_cross_task, source_keys,
                                          chunksize=max(1, len(source_keys) // (processes * 4) or 1)))
 
    edges = []
    for hits in all_hits:
        edges.extend(hits)
    return edges

def _format_node(node):
    seq_id, orientation = node
    return f"{seq_id}({orientation})"

def _normalize_cycle(nodes):
    """Pivots node list to start from the 'smallest' one, in order to identitfy similar cycles, no matter the starting node."""
    n = len(nodes)
    best = None
    for i in range(n):
        rotated = tuple(nodes[i:] + nodes[:i])
        if best is None or rotated < best:
            best = rotated
    return best

def find_cycles(edges, max_cycle_length, max_cycles_report=200, max_dfs_steps=300_000):
    """Returns the cycles found in the graph defined by the edge list. Will be stop in case of repetitive data (truncated is True)."""
    adjacency = defaultdict(list)
    for e in edges:
        adjacency[e["from"]].append((e["to"], e["overlap_len"], e["mismatch_rate"]))
 
    found = []
    seen = set()
    steps = 0
    truncated = False
 
    for start in sorted(adjacency.keys()):
        stack = [(start, [start], {start[0]}, [])]
        while stack:
            steps += 1
            if steps > max_dfs_steps:
                truncated = True
                break
            node, path, used_ids, path_edges = stack.pop()
            for nxt, ov_len, rate in adjacency.get(node, []):
                if nxt == start and len(path) >= 2:
                    normalized = _normalize_cycle(path)
                    if normalized not in seen:
                        seen.add(normalized)
                        found.append({
                            "nodes": path,
                            "edges": path_edges + [(node, nxt, ov_len, rate)],
                        })
                        if len(found) >= max_cycles_report:
                            return found, truncated
                elif nxt[0] not in used_ids and len(path) < max_cycle_length:
                    stack.append((nxt, path + [nxt], used_ids | {nxt[0]}, path_edges + [(node, nxt, ov_len, rate)]))
        if truncated:
            break
 
    return found, truncated

def get_circulars(fasta, selection = [], min_overlap = 20, max_overlap = 100, max_mismatch_rate = 0.02, seed_length = 13, max_cycle_length = 6, proc = 2):
    """Retrieves circular sequences by matching the ends of each sequence in the provided fasta (and the selection), with themselves and other sequences."""
    circulars = {}
    
    sequences = parse_fasta(fasta)
    if not sequences:
        print("No sequence in provided fasta file", file=sys.stderr)
        sys.exit(1)
    
    # keeping only selection
    sequences = {seq_id:sequence for seq_id, sequence in sequences.items() if seq_id in selection or len(selection) == 0}

 
    # Individual circularity
    self_hits = check_self_circularity(
        sequences, seed_length, min_overlap, max_overlap, max_mismatch_rate, processes=proc
    )
    
    if self_hits:
        for hit in self_hits:
            seq_id = hit["sequences"][0]
            circulars[seq_id] = f"Self-circular\n({hit['overlap_len']} pb identity, mismatch {hit['mismatch_rate']*100:.1f}%)"
 
    # Combined circularity between sequences
    all_edges = check_cross_circularity(
        sequences, seed_length, min_overlap, max_overlap, max_mismatch_rate, processes=proc
    )
    direct_hits = [e for e in all_edges if e["from"][1] == "+"]
    if direct_hits:
        for hit in direct_hits:
            id_a = hit["from"][0]
            id_b = hit["to"][0]
            circulars[id_a] = f"Overlap with {id_b}\n({hit['overlap_len']} pb identity, mismatch {hit['mismatch_rate']*100:.1f}%)"
            circulars[id_b] = f"Overlap with {id_a}\n({hit['overlap_len']} pb identity, mismatch {hit['mismatch_rate']*100:.1f}%)"
 
    # Cycles detection (likely circularity)
    cycles, truncated = find_cycles(all_edges, max_cycle_length)
    if cycles:
        cycles.sort(key=lambda c: len(c["nodes"]))
        for cycle in cycles:
            nodes = [_format_node(node) for node in cycle["nodes"]]
            for node in nodes:
                circulars[node] = f"Cycle detected\nwith {','.join([node2 for node2 in nodes if node2 != node])}"
    return circulars
